### ISSUE TITLE
Rogue core skills inherent attack speed multiplier?

### ISSUE THREAD

**Issue by esvban** [Lothrik/diablo4-build-calc#37]
I'm pretty sure some of the rogue core skills have different attack speed multipliers. Rapidfire fires much slower than barrage, and also locks you in place until done firing. How did you get the attack speed multiplier for the sorc skills?

**Comment by Lothrik** [comment]
I added an explanation for this to the FAQ:

Each skill has its own unique attack animation. Blizzard occasionally wants certain skills to be faster, or slower. Rather than rework the animation directly they simply multiply how quickly your character executes that specific skill.

I datamine that multiplier as the "attack speed multiplier" you see on certain skills.

One skill having a significantly higher multiplier than another doesn't necessarily mean that skill is faster, just that it was slower at some point in the past.

Just as an example, Maul was buffed between build 39858 and 41428 to be 10% faster — that change can be seen [here](https://lothrik.github.io/diablo4-build-calc/history/39858-41428.html).
